server :
  #URL : 'redis://virujhliveredis-001.ysl6gq.0001.aps1.cache.amazonaws.com:6379'
   URL : 'redis://redis-dev-server:6379'

database :
  type : 'postgres'
  username : 'postgres'
  password : 'postgres'
  host: 'virujh-dev-new.cjxvyzcwczxh.ap-south-1.rds.amazonaws.com'
  database : 'liveauth'
  port : 5432
  synchronize : false
  
JWT :
  expiresIn : 36000000
  secret : 'topSecret51'
  defaultStrategy : 'jwt'